# Generated by Django 5.0 on 2023-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('poster', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
